# Generated by Django 2.2.4 on 2019-08-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheVoterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('s_code', models.IntegerField()),
                ('c_code', models.IntegerField()),
                ('d_code', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('aLine1', models.CharField(max_length=500)),
                ('aLine2', models.CharField(max_length=500)),
                ('aadhar_no', models.BigIntegerField()),
                ('voter_photo', models.ImageField(upload_to='')),
                ('aadhar_card', models.ImageField(upload_to='')),
                ('address_proof', models.ImageField(upload_to='')),
            ],
        ),
    ]
