# Generated by Django 2.2.4 on 2019-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('aadhar_no', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_card', models.ImageField(upload_to='')),
                ('address_proof', models.ImageField(upload_to='')),
                ('voter_photo', models.ImageField(upload_to='')),
                ('login_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CacheVoterData',
        ),
    ]
