# Generated by Django 2.2.4 on 2019-08-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0002_auto_20190810_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='aadhar_card',
            new_name='govtID_card',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='connectionHash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
