# Generated by Django 2.2.4 on 2019-08-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0003_auto_20190811_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='aadhar_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
