# Generated by Django 2.2.4 on 2019-08-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0004_auto_20190811_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='aadhar_no',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
