# Generated by Django 2.2.4 on 2019-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0005_auto_20190811_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheVoterData',
            fields=[
                ('voter_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('aadhar_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('aLine1', models.CharField(max_length=500)),
                ('aLine2', models.CharField(max_length=500)),
                ('s_code', models.IntegerField()),
                ('c_code', models.IntegerField()),
                ('d_code', models.IntegerField()),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
