# Generated by Django 2.2.4 on 2019-08-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0006_cachevoterdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='voterID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
