# Generated by Django 2.2.4 on 2019-08-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0008_task_workerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='connectionHash',
            new_name='connectionurl',
        ),
    ]
