# Generated by Django 2.2.4 on 2019-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0009_auto_20190812_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='connectionurl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
