# Generated by Django 2.2.4 on 2019-08-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0010_auto_20190812_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='connectionHash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
