# Generated by Django 2.2.4 on 2019-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0011_task_connectionhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
