# Generated by Django 2.2.4 on 2019-08-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoterform', '0012_workerprofile_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='login_token',
        ),
    ]
