# Generated by Django 2.2.4 on 2019-08-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='private_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event_token',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
