# Generated by Django 2.2.4 on 2019-08-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regapi', '0002_auto_20190814_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapi.Event')),
            ],
        ),
    ]
