# Generated by Django 2.2.4 on 2019-08-14 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapi', '0003_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='callback_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
