# Generated by Django 2.2.4 on 2019-08-14 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapi', '0004_api_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='redirect_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
